import{a as p,S,i as n}from"./assets/vendor-5401a4b0.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&o(l)}).observe(document,{childList:!0,subtree:!0});function a(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(t){if(t.ep)return;t.ep=!0;const r=a(t);fetch(t.href,r)}})();const u=15;p.defaults.baseURL="https://pixabay.com";const O="/api/",P="42750923-b31641a9e28119200a05c3b82";async function g(s,e){return await p.get(`${O}`,{params:{key:P,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:u,page:e}})}const m=document.querySelector(".gallery");function B(s){return s.map(e=>`<li class="gallery-item">
    <a href="${e.largeImageURL}" class="gallery-link">
    <img class="gallery-img" src="${e.webformatURL}" alt="${e.tags}" loading="lazy"/>
    </a>
    <div class="gallery-container">
    <p class="gallery-text">Likes<span>${e.likes}</span></p>
      <p class="gallery-text">Views<span>${e.views}</span></p>
      <p class="gallery-text">Comments<span>${e.comments}</span></p>
      <p class="gallery-text">Downloads<span>${e.downloads}</span></p>
    </div>
  </li>`).join(" ")}function y(s){m.insertAdjacentHTML("beforeend",B(s))}const d=document.querySelector("form"),q=document.querySelector("input"),f=document.querySelector(".pagin-button"),h=document.querySelector(".loader");let i=1;function M(s){const a=s.getBoundingClientRect().height*2;window.scrollBy({top:a,behavior:"smooth"})}function w(){h.classList.remove("is-hidden")}function c(){h.classList.add("is-hidden")}function z(){f.classList.remove("is-hidden")}function L(){f.classList.add("is-hidden")}function v(s,e){s<e&&(n.warning({message:"We are sorry, but youve reached the end of search results.!",position:"center",close:!1,closeOnClick:!0,progressBar:!1,messageSize:30,timeout:!1,displayMode:1}),L())}async function $(s){s.preventDefault(),i=1,w(),m.innerHTML="";const e=d.elements.field.value;if(e)try{const a=await g(e,i);a.data.total!==0?(y(a.data.hits),b.refresh(),z(),v(a.data.hits.length,u)):(n.warning({message:"Sorry, there are no images matching your search query. Please try again!",position:"center",close:!1,closeOnClick:!0,progressBar:!1,messageSize:30,timeout:!1,displayMode:1}),q.value="",L())}catch{n.warning({message:"Ups, something wrong bad. Please try again!",position:"center",close:!1,closeOnClick:!0,progressBar:!1,messageSize:30,timeout:!1,displayMode:1})}finally{c()}else n.warning({message:"Please enter the name of the picture!",position:"center",close:!1,closeOnClick:!0,progressBar:!1,messageSize:30,timeout:!1,displayMode:1,transitionIn:"flipInX"}),c()}async function x(s){i++,s.preventDefault(),w();const e=d.elements.field.value;try{const a=await g(e,i);y(a.data.hits),b.refresh();const o=document.querySelector(".gallery-item");M(o),v(a.data.hits.length,u)}catch{n.warning({message:"Ups, something wrong bad. Please try again!",position:"center",close:!1,closeOnClick:!0,progressBar:!1,messageSize:30,timeout:!1,displayMode:1})}finally{c()}}d.addEventListener("submit",$);f.addEventListener("click",x);const b=new S(".gallery a",{captionsData:"alt",captionDelay:"250"});
//# sourceMappingURL=commonHelpers.js.map
