import{a as p,S as b,i as o}from"./assets/vendor-5401a4b0.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const u=15;p.defaults.baseURL="https://pixabay.com";const S="/api/",O="42750923-b31641a9e28119200a05c3b82";async function g(a,e){return await p.get(`${S}`,{params:{key:O,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:u,page:e}})}const m=document.querySelector(".gallery");function P(a){return a.map(e=>`<li class="gallery-item">
    <a href="${e.largeImageURL}" class="gallery-link">
    <img class="gallery-img" src="${e.webformatURL}" alt="${e.tags}" loading="lazy"/>
    </a>
    <div class="gallery-container">
    <p class="gallery-text">Likes<span>${e.likes}</span></p>
      <p class="gallery-text">Views<span>${e.views}</span></p>
      <p class="gallery-text">Comments<span>${e.comments}</span></p>
      <p class="gallery-text">Downloads<span>${e.downloads}</span></p>
    </div>
  </li>`).join(" ")}function y(a){m.insertAdjacentHTML("beforeend",P(a))}const d=document.querySelector("form"),B=document.querySelector("input"),f=document.querySelector(".pagin-button"),h=document.querySelector(".loader");let i=1;function M(a){const s=a.getBoundingClientRect().height*2;window.scrollBy({top:s,behavior:"smooth"})}function w(){h.classList.remove("is-hidden")}function L(){h.classList.add("is-hidden")}function q(){f.classList.remove("is-hidden")}function c(){f.classList.add("is-hidden")}async function z(a){a.preventDefault(),i=1,w(),m.innerHTML="";const e=d.elements.field.value;if(e)try{const s=await g(e,i);s.data.total!==0?(y(s.data.hits),v.refresh(),q(),s.data.hits.length<u&&(o.warning({message:"We are sorry, but youve reached the end of search results.!",position:"center",close:!1,closeOnClick:!0,progressBar:!1,messageSize:30,timeout:!1,displayMode:1}),c())):(o.warning({message:"Sorry, there are no images matching your search query. Please try again!",position:"center",close:!1,closeOnClick:!0,progressBar:!1,messageSize:30,timeout:!1,displayMode:1}),B.value="",c())}catch{o.warning({message:"Ups, something wrong bad. Please try again!",position:"center",close:!1,closeOnClick:!0,progressBar:!1,messageSize:30,timeout:!1,displayMode:1})}else o.warning({message:"Please enter the name of the picture!",position:"center",close:!1,closeOnClick:!0,progressBar:!1,messageSize:30,timeout:!1,displayMode:1,transitionIn:"flipInX"});L()}async function C(a){i++,a.preventDefault(),w();const e=d.elements.field.value;try{const s=await g(e,i);y(s.data.hits),v.refresh();const n=document.querySelector(".gallery-item");M(n),s.data.hits.length<u&&(o.warning({message:"We are sorry, but youve reached the end of search results.!",position:"center",close:!1,closeOnClick:!0,progressBar:!1,messageSize:30,timeout:!1,displayMode:1}),c())}catch{o.warning({message:"Ups, something wrong bad. Please try again!",position:"center",close:!1,closeOnClick:!0,progressBar:!1,messageSize:30,timeout:!1,displayMode:1})}L()}d.addEventListener("submit",z);f.addEventListener("click",C);const v=new b(".gallery a",{captionsData:"alt",captionDelay:"250"});
//# sourceMappingURL=commonHelpers.js.map
